1. importing the libary

In [56]:
import pandas as pd
import numpy as np


2. uploading the csv file and diving the part that will use in predition parameter ie. X 
and Y as the predicted result.

In [57]:
dataset = pd.read_csv("insurance.csv")
x = dataset.iloc[:,:-1].values
y = dataset.iloc[:,-1].values

In [58]:
# showing the data in the data that will use for the predition

pd.DataFrame(x)
# showing the data types with its coloum name
dataset.info()
# showinf the mean , median , min etc of the data
dataset.describe()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1338 entries, 0 to 1337
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   age       1338 non-null   int64  
 1   sex       1338 non-null   object 
 2   bmi       1338 non-null   float64
 3   children  1338 non-null   int64  
 4   smoker    1338 non-null   object 
 5   region    1338 non-null   object 
 6   charges   1338 non-null   float64
dtypes: float64(2), int64(2), object(3)
memory usage: 73.3+ KB


age          bmi     children       charges
count  1338.000000  1338.000000  1338.000000   1338.000000
mean     39.207025    30.663397     1.094918  13270.422265
std      14.049960     6.098187     1.205493  12110.011237
min      18.000000    15.960000     0.000000   1121.873900
25%      27.000000    26.296250     0.000000   4740.287150
50%      39.000000    30.400000     1.000000   9382.033000
75%      51.000000    34.693750     2.000000  16639.912515
max      64.000000    53.130000     5.000000  63770.428010

In [59]:
dataset["charges"].describe()

count     1338.000000
mean     13270.422265
std      12110.011237
min       1121.873900
25%       4740.287150
50%       9382.033000
75%      16639.912515
max      63770.428010
Name: charges, dtype: float64

3. data preprocess 
converting the male and female into 0 ,1 

In [60]:
from sklearn.preprocessing import LabelEncoder
Le = LabelEncoder()
x[:,1] = Le.fit_transform(x[:,1])


In [61]:
# showing the newly changed x
print(x)

[[19 0 27.9 0 'yes' 'southwest']
 [18 1 33.77 1 'no' 'southeast']
 [28 1 33.0 3 'no' 'southeast']
 ...
 [18 0 36.85 0 'no' 'southeast']
 [21 0 25.8 0 'no' 'southwest']
 [61 0 29.07 0 'yes' 'northwest']]


In [62]:
# conventing the yes , no into 1,0
 
x[:,4] = Le.fit_transform(x[:,4])


In [63]:
print(x)

[[19 0 27.9 0 1 'southwest']
 [18 1 33.77 1 0 'southeast']
 [28 1 33.0 3 0 'southeast']
 ...
 [18 0 36.85 0 0 'southeast']
 [21 0 25.8 0 0 'southwest']
 [61 0 29.07 0 1 'northwest']]


4. pre processing with the the location like south west east ...

In [64]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
ct = ColumnTransformer(transformers=[('encoding',OneHotEncoder(),[5])],remainder='passthrough')
x = np.array(ct.fit_transform(x))

In [65]:
# printing the x values 
print(x)

[[0.0 0.0 0.0 ... 27.9 0 1]
 [0.0 0.0 1.0 ... 33.77 1 0]
 [0.0 0.0 1.0 ... 33.0 3 0]
 ...
 [0.0 0.0 1.0 ... 36.85 0 0]
 [0.0 0.0 0.0 ... 25.8 0 0]
 [0.0 1.0 0.0 ... 29.07 0 1]]


5. splitong the values into the train and test test

In [66]:

from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.2,random_state=0) 

6. traing of the training sets

In [67]:


from sklearn.ensemble import RandomForestRegressor 
le = RandomForestRegressor(n_estimators=10,random_state=0)
le.fit(x_train,y_train)

RandomForestRegressor(n_estimators=10, random_state=0)

7. predicting the values of test set  

In [68]:
y_pred = le.predict(x_test)
np.set_printoptions(precision=2)
print(np.concatenate( (y_test.reshape(len(x_test),1)  , y_pred.reshape(len(y_pred),1)),1  ))

[[ 9724.53 11812.3 ]
 [ 8547.69  8487.68]
 [45702.02 44973.46]
 [12950.07 13294.77]
 [ 9644.25  9306.01]
 [ 4500.34  9930.7 ]
 [ 2198.19  2031.53]
 [11436.74 10563.36]
 [ 7537.16  7210.22]
 [ 5425.02  8008.23]
 [ 6753.04  6598.43]
 [10493.95 15902.45]
 [ 7337.75  9720.64]
 [ 4185.1   6948.49]
 [18310.74 23600.31]
 [10702.64 13997.1 ]
 [12523.6  13509.14]
 [ 3490.55  8706.11]
 [ 6457.84  6593.29]
 [33475.82 34043.87]
 [23967.38 23612.29]
 [12643.38 12546.88]
 [23045.57 13588.75]
 [23065.42 27910.82]
 [ 1674.63  1558.35]
 [ 4667.61 11156.06]
 [ 3732.63 10384.21]
 [ 7682.67  7137.49]
 [ 3756.62  3779.35]
 [ 8413.46 10536.38]
 [ 8059.68  7442.53]
 [48970.25 48502.61]
 [12979.36 14026.01]
 [20630.28 10427.79]
 [14571.89 15464.59]
 [ 4137.52  3881.92]
 [ 8347.16  8362.  ]
 [51194.56 37406.27]
 [40003.33 40938.03]
 [ 1880.49  2814.59]
 [ 5458.05  9419.51]
 [ 2867.12  2941.16]
 [20149.32 20534.03]
 [47496.49 47337.51]
 [36149.48 37046.89]
 [26018.95  7664.52]
 [19749.38 13997.1 ]
 [ 6940.91  6